### ISSUE TITLE
Barfs on circular structures

### ISSUE THREAD

**Issue by dbushong** [EndangeredMassa/format-error#2]
It would be nice if format-error could survive being handed potentially circular data structures.

```
TypeError: Converting circular structure to JSON
    at Object.stringify (native)
    at makeSimple (/.../node_modules/format-error/index.js:36:28)
    at format (/.../node_modules/format-error/index.js:39:21)
    ...
```

**Comment by EndangeredMassa** [comment]
I think that this module shouldn't really exist. I'd rather fix this in prettyjson itself, but it needs better Error rendering support as well.
